# Generated by Django 4.0.6 on 2022-08-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.book'),
        ),
    ]
