# Generated by Django 4.0.6 on 2022-08-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_rename_author_review_authorreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can read all books')]},
        ),
    ]
