# Generated by Django 4.0.6 on 2022-08-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'can readd books')]},
        ),
    ]
