# Generated by Django 4.1.1 on 2022-09-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='session',
            field=models.CharField(choices=[('asi', 'asia'), ('eur', 'europe'), ('us', 'usa')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
