# Generated by Django 4.1.1 on 2022-09-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('currency', models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('gbp', 'gbp'), ('aud', 'aud'), ('nzd', 'nzd'), ('cad', 'cad'), ('jpy', 'jpy'), ('cny', 'cny')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('previous', models.CharField(max_length=100)),
                ('actual', models.CharField(max_length=100)),
            ],
        ),
    ]
