# Generated by Django 4.1.1 on 2022-09-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_economiccalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'news'), ('article', 'article')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='session',
            field=models.CharField(choices=[('asi', 'asia'), ('eur', 'europe'), ('us', 'usa')], max_length=10),
        ),
    ]
