# Generated by Django 4.1.1 on 2022-10-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_type_alter_post_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='economiccalender',
            name='forecast',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
